theme: jekyll-theme-so-simple
title: Multi-Echo Spin-Echo quantitative high-resolution R2

github:
  repository_url: https://github.com/schmidt-jo/PyMRItools
  owner_name: Jochen Schmidt
  owner_url: https://github.com/schmidt-jo

url: "https://schmidt-jo.github.io"
baseurl: "/mese_t2_paper"
permalink: pretty
remote_theme: "mmistakes/so-simple-theme@3.2.0"
defaults:
  - scope:
      path: ""
    values:
      layout: default
