theme: jekyll-theme-midnight
title: Q2 Paper Visualizations
name: Q2 Paper Visualizations
tagline: All things considered, it was good

github:
  repository_url: https://github.com/schmidt-jo/PyMRItools
  owner_name: Jochen Schmidt aka Smity Joe
  owner_url: https://github.com/schmidt-jo

url: "https://schmidt-jo.github.io"
baseurl: "/mese_t2_paper"
permalink: pretty
defaults:
  - scope:
      path: ""
    values:
      layout: default
