remote_theme: "mmistakes/so-simple-theme@3.2.0"
title: Multi-Echo Spin-Echo quantitative high-resolution R2

repository: schmidt-jo/mese_t2_paper
skin: "/assets/css/skins/dark.css"

author:
  name: Jochen Schmidt
  email: jschmidt@cbs.mpg.de

github:
  repository_url: https://github.com/schmidt-jo/PyMRItools
  owner_name: Jochen Schmidt
  owner_url: https://github.com/schmidt-jo

url: "https://schmidt-jo.github.io"
baseurl: "/mese_t2_paper"
permalink: pretty
defaults:
  - scope:
      path: ""
    values:
      layout: default
