theme: jekyll-theme-midnight
title: Multi-Echo Spin-Echo R2 manuscript

github:
  repository_url: https://github.com/schmidt-jo/PyMRItools
  owner_name: Jochen Schmidt
  owner_url: https://github.com/schmidt-jo

url: "https://schmidt-jo.github.io"
baseurl: "/mese_t2_paper"
permalink: pretty
defaults:
  - scope:
      path: ""
    values:
      layout: default
