theme: jekyll-theme-midnight
title: This is the header of the webpage

github:
  repository_url: https://github.com/schmidt-jo/PyMRItools
  owner_name: Jochen Schmidt aka Smity Joe
  owner_url: https://github.com/schmidt-jo

url: "https://schmidt-jo.github.io"
baseurl: "/mese_t2_paper"
permalink: pretty
defaults:
  - scope:
      path: ""
    values:
      layout: default
