name: Deploy GitHub Pages with LFS

on:
  push:
    branches: [main]  # Or your default branch

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository with LFS
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Set up GitHub Pages
      uses: actions/configure-pages@v4

    - name: Build with Jekyll
      run: |
        bundle install
        bundle exec jekyll build

    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./_site

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4

